### PR TITLE
check manually modified files 

### PR DESCRIPTION
**Pull request by AkihiroSuda**
The first commit is a dupe of #44 
The second commit is the substantial part.

I'll rebase when #44 gets merged.

cc @dnephin

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Weird, locally CI green

**Comment by LK4D4** [comment]
I don't like this check :/ It doesn't look like it belongs to this tool.

**Comment by dnephin** [comment]
@LK4D4 this is the thing we really need.

Don't you think that everyone who uses a git committed `vendor/` directory needs to perform this check?

**Comment by LK4D4** [comment]
@dnephin I'm pretty sure that almost nobody does that :) 
But that's not the point, they totally should. Just I think that it's easy to do it outside vndr and the feature itself has nothing to do with anything that vndr does - no work with packages. The only common point is "vendor/" location.

**Comment by AkihiroSuda** [comment]
ok, closing this PR

@dnephin @vieux 
Please refer to https://forums.mobyproject.org/t/proposal-split-containerize-hack-validate/32/3?u=akihirosuda

**Pull request closed without merging**
