### PR TITLE
Dont rm -rf all the repos

### PR DESCRIPTION
**Pull request by giuseppe**

### CODE REVIEW

**Comment by giuseppe** [comment]
@LK4D4 this should fix the issue with refetching the entire repositories each time.

There is a new flag -clean-vcs to keep the previous behavior

**Comment by LK4D4** [comment]
@giuseppe @runcom I really wonder if you should try https://github.com/rancher/trash instead. It keeps vcs cache and stuff and it's better fit for your vendoring model. It can read same config format, so you just need to replace vndr binary with trash. 
I'm okay with merging this, but just maybe we can keep vndr simpler and you happier while we wait for official vendoring tool. Let me know your thoughts. 
Thanks!

**Comment by runcom** [comment]
@LK4D4 yeah we can try that tool while waiting golang's without messing this repository :) thanks!

**Comment by runcom** [comment]
@giuseppe we can use glide and glide-vc to keep vendoring in c/image (I think)

**Comment by giuseppe** [comment]
@LK4D4 in case it might be useful to you, I've modified the patch to not change the current behaviour but an user needs to specify `-keep-vcs-files` to keep the vcs files.

**Comment by LK4D4** [comment]
@giuseppe I'm reluctant to merge it because trash much better handles that use-case and I don't want to create illusion that vndr can be replacement in that case.
Thanks for your efforts, anyway! I appreciate it.

**Pull request closed without merging**
